version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    networks:
      default:
      static:
        ipv4_address: 172.40.0.10
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
    - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    volumes:
      - ./adminer.css:/var/www/html/adminer.css

networks:
  default:   
  static:
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/16
  web:
    external: true



        